// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pigulator.Data;

namespace Pigulator.Migrations
{
    [DbContext(typeof(PigulatorContext))]
    [Migration("20200914181544_IntialCreate")]
    partial class IntialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pigulator.Models.Pigs", b =>
                {
                    b.Property<long>("PigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("HalfPig")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("WholePig")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("PigID");

                    b.ToTable("Pigulator");
                });
#pragma warning restore 612, 618
        }
    }
}
